/**
 * Lista de erros de digitação e abreviações conhecidos do pt-BR, usada SÓ para desenhar o
 * sublinhado vermelho sob a palavra enquanto o atendente digita. Nada aqui reescreve o texto.
 *
 * Existia também uma correção automática por similaridade de letras (sugeria a palavra do
 * vocabulário a 1 letra de distância). Foi removida: tratava "falta a letra r" como erro de
 * digitação e transformava verbo corretamente conjugado em infinitivo ("envia" -> "enviar",
 * "manda" -> "mandar", "verifica" -> "verificar"), errando o tempo verbal da frase - e
 * sublinhava essas palavras como se estivessem erradas.
 */

// Word-level replacements (normalized lowercase keys)
export const WORD_REPLACEMENTS: Record<string, string> = {
  // Typos curtos, listados explicitamente
  'gete': 'gente',
  'genet': 'gente',
  'quado': 'quando',
  'quanmdo': 'quando',
  'qaundo': 'quando',
  'quadno': 'quando',
  'obigado': 'obrigado',
  'obrigao': 'obrigado',
  'enviao': 'enviado',
  'mensagen': 'mensagem',
  'mensagens': 'mensagens',
  'homen': 'homem',
  'onten': 'ontem',
  'alguen': 'alguém',
  'ninguen': 'ninguém',
  'tamben': 'também',
  'bem-vindo': 'bem-vindo',
  'agendaar': 'agendar',
  'conversaar': 'conversar',
  'oque': 'o que',
  'msm': 'mesmo',
  'qdo': 'quando',
  'qnd': 'quando',
  'qto': 'quanto',
  'agr': 'agora',
  'amnh': 'amanhã',
  'hj': 'hoje',
  'blz': 'beleza',
  'vlw': 'valeu',
  'flw': 'falou',
  // Common informal abbreviations
  'vc': 'você',
  'vcs': 'vocês',
  'tb': 'também',
  'tbm': 'também',
  'pq': 'porque',
  'oq': 'o que',
  'kd': 'cadê',
  'td': 'tudo',
  'tds': 'todos',
  'blz': 'beleza',
  'vlw': 'valeu',
  'cmg': 'comigo',
  'ctg': 'contigo',
  'pfv': 'por favor',
  'pls': 'por favor',
  'porfa': 'por favor',
  'msg': 'mensagem',
  'msgs': 'mensagens',
  'zap': 'WhatsApp',
  'whats': 'WhatsApp',
  'wpp': 'WhatsApp',
  'obg': 'obrigado',
  'obgd': 'obrigado',
  'obgda': 'obrigada',
  'brigado': 'obrigado',
  'brigada': 'obrigada',
  'dnada': 'de nada',

  // Common phonetic / spelling mistakes
  'senho': 'senhor',
  'senhorr': 'senhor',
  'menas': 'menos',
  'seje': 'seja',
  'esteje': 'esteja',
  'poblema': 'problema',
  'pobrema': 'problema',
  'probrema': 'problema',
  'poblemas': 'problemas',
  'probremas': 'problemas',
  'fais': 'faz',
  'geito': 'jeito',
  'excessao': 'exceção',
  'excessão': 'exceção',
  'escessao': 'exceção',
  'escecao': 'exceção',
  'enxergar': 'enxergar',
  'enchergar': 'enxergar',
  'mecher': 'mexer',
  'meche': 'mexe',
  'paralizar': 'paralisar',
  'analizar': 'analisar',
  'analize': 'análise',
  'pesquiza': 'pesquisa',

  // Missing accents - Technical, Equipment & Parts
  'substituidos': 'substituídos',
  'substituido': 'substituído',
  'substituida': 'substituída',
  'substituidas': 'substituídas',
  'maquina': 'máquina',
  'maquinas': 'máquinas',
  'equipamento': 'equipamento',
  'equipamentos': 'equipamentos',
  'eletrica': 'elétrica',
  'eletricas': 'elétricas',
  'eletrico': 'elétrico',
  'eletricos': 'elétricos',
  'eletronica': 'eletrônica',
  'eletronicas': 'eletrônicas',
  'eletronico': 'eletrônico',
  'eletronicos': 'eletrônicos',
  'mecanica': 'mecânica',
  'mecanicas': 'mecânicas',
  'mecanico': 'mecânico',
  'mecanicos': 'mecânicos',
  'tecnico': 'técnico',
  'tecnica': 'técnica',
  'tecnicos': 'técnicos',
  'tecnicas': 'técnicas',
  'peca': 'peça',
  'pecas': 'peças',
  'orcamento': 'orçamento',
  'orcamentos': 'orçamentos',
  'servico': 'serviço',
  'servicos': 'serviços',
  'laboratorio': 'laboratório',
  'laboratorios': 'laboratórios',
  'modulo': 'módulo',
  'modulos': 'módulos',
  'codigo': 'código',
  'codigos': 'códigos',
  'numero': 'número',
  'numeros': 'números',
  'revisao': 'revisão',
  'revisoes': 'revisões',
  'manutencao': 'manutenção',
  'manutencoes': 'manutenções',
  'calibracao': 'calibração',
  'calibracoes': 'calibrações',
  'garantia': 'garantia',
  'garantias': 'garantias',
  'conserto': 'conserto',
  'consertos': 'consertos',
  'valvula': 'válvula',
  'valvulas': 'válvulas',
  'fusivel': 'fusível',
  'fusiveis': 'fusíveis',
  'bateria': 'bateria',
  'baterias': 'baterias',

  // Missing accents - Common verbs & auxiliary words
  'nao': 'não',
  'sao': 'são',
  'estao': 'estão',
  'irao': 'irão',
  'sera': 'será',
  'serao': 'serão',
  'esta': 'está',
  'estara': 'estará',
  'estarao': 'estarão',
  'tambem': 'também',
  'alguem': 'alguém',
  'ninguem': 'ninguém',
  'ate': 'até',
  'ja': 'já',
  'so': 'só',
  'la': 'lá',
  'ca': 'cá',
  'eh': 'é',
  'ta': 'está',
  'to': 'estou',
  'pra': 'para',
  'pro': 'para o',
  'pros': 'para os',
  'pras': 'para as',
  'concluido': 'concluído',
  'concluida': 'concluída',
  'concluidos': 'concluídos',
  'concluidas': 'concluídas',
  'valido': 'válido',
  'valida': 'válida',
  'validos': 'válidos',
  'validas': 'válidas',
  'invalido': 'inválido',
  'invalida': 'inválida',

  // Missing accents - Business & Communication
  'atencao': 'atenção',
  'posicao': 'posição',
  'posicoes': 'posições',
  'autorizacao': 'autorização',
  'autorizacoes': 'autorizações',
  'solucao': 'solução',
  'solucoes': 'soluções',
  'avaliacao': 'avaliação',
  'avaliacoes': 'avaliações',
  'confirmacao': 'confirmação',
  'confirmacoes': 'confirmações',
  'informacao': 'informação',
  'informacoes': 'informações',
  'condicao': 'condição',
  'condicoes': 'condições',
  'situacao': 'situação',
  'situacoes': 'situações',
  'solicitacao': 'solicitação',
  'solicitacoes': 'solicitações',
  'opcao': 'opção',
  'opcoes': 'opções',
  'direcao': 'direção',
  'disposicao': 'disposição',
  'comunicacao': 'comunicação',
  'declaracao': 'declaração',
  'preco': 'preço',
  'precos': 'preços',
  'duvida': 'dúvida',
  'duvidas': 'dúvidas',
  'horario': 'horário',
  'horarios': 'horários',
  'periodo': 'período',
  'periodos': 'períodos',
  'proximo': 'próximo',
  'proxima': 'próxima',
  'proximos': 'próximos',
  'proximas': 'próximas',
  'ultimo': 'último',
  'ultima': 'última',
  'ultimos': 'últimos',
  'ultimas': 'últimas',
  'facil': 'fácil',
  'faceis': 'fáceis',
  'dificil': 'difícil',
  'dificeis': 'difíceis',
  'possivel': 'possível',
  'possiveis': 'possíveis',
  'impossivel': 'impossível',
  'impossiveis': 'impossíveis',
  'disponivel': 'disponível',
  'disponiveis': 'disponíveis',
  'responsavel': 'responsável',
  'responsaveis': 'responsáveis',
  'util': 'útil',
  'uteis': 'úteis',
  'inutil': 'inútil',
  'inuteis': 'inúteis',
  'rapido': 'rápido',
  'rapida': 'rapida',
  'rapidos': 'rápidos',
  'rapidas': 'rápidas',
  'otimo': 'ótimo',
  'otima': 'ótima',
  'otimos': 'ótimos',
  'otimas': 'ótimas',
  'pessimo': 'péssimo',
  'pessima': 'péssima',
  'publico': 'público',
  'pagina': 'página',
  'paginas': 'páginas',
  'gerencia': 'gerência',
  'exito': 'êxito',
  'inicio': 'início',
  'previo': 'prévio',
  'previa': 'prévia',
  'criterio': 'critério',
  'criterios': 'critérios',
  'historico': 'histórico',
  'historicos': 'históricos',
  'politica': 'política',
  'politicas': 'políticas'
};

/** True só para erro/abreviação da lista acima - nunca por "palavra parecida". */
export function isMisspelled(word: string): boolean {
  if (!word) return false;
  const lower = word.toLowerCase();
  const rep = WORD_REPLACEMENTS[lower];
  return !!rep && rep.toLowerCase() !== lower;
}
